### ISSUE TITLE
文件没有后缀的情况

### ISSUE THREAD

**Issue by xuelongqy** [kekingcn/kkFileView#106]
我大概看了一下源码的实现，使用的是url解析文件后缀。其实很多时候文件没有后缀，包括下载以后。可否这样去实现呢，下载文件的时候通过文件头去验证文件类型(或者下载文件后，因为有些文件类型的文件头是一致的)。然后再用相应的视图展示。个人建议，望采纳

**Comment by klboke** [comment]
我们已经支持文件流的模式哦

**Comment by xuelongqy** [comment]
您好，请问如何开启支持呢？实在没有找到🤣

**Comment by klboke** [comment]
看我们的文档

**Comment by xuelongqy** [comment]
好的，找到了。非常感谢
