### ISSUE TITLE
could not store document: 123.html; errorCode: 2074]

### ISSUE THREAD

**Issue by mydbp** [kekingcn/kkFileView#110]
org.artofsolving.jodconverter.office.OfficeException: could not store document: 123.html; errorCode: 2074] with root cause

同一个 xlsx文件
window环境下，我测试是可以的，
然后我发布项目到  liunx主机，访问就报这个错了，
有人遇到这种问题吗，怎么解决的？求协助

**Comment by mydbp** [comment]
已经弄好了，谢谢。

**Comment by wangyunchuan2012** [comment]
> 已经弄好了，谢谢。

请问是如何解决的

**Comment by mydbp** [comment]
好久了，忘记了；
1、你跟踪下看看吧，我记得在线预览流程是这样，首先下载文件，然后是转换文件，然后在查看pdf；你看下，下载的文件有问题没，然后 转换pdf 有问题没(看看文件大小，从linux主机上拖下来看看)。一步一步看看。
2、我linux 上用的&nbsp;LibreOffice




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kekingcn/kkFileView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 上午10:57
收件人:&nbsp;"kekingcn/kkFileView"<kkFileView@noreply.github.com&gt;;
抄送:&nbsp;"dbp"<1565229106@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [kekingcn/kkFileView] could not store document: 123.html; errorCode: 2074] (#110)





  
已经弄好了，谢谢。
  
请问是如何解决的
