### ISSUE TITLE
建议将 使用的OpenOffice 换成同开源的LibreOffice

### ISSUE THREAD

**Issue by xuren11** [kekingcn/kkFileView#160]
如题。 在对word转pdf时。 对于那种直接用拖拽操作 把图片拖进word的情况。 OpenOffice转pdf的时候 会 丢失掉这个图片。 但是 libreOffice的则不会

**Comment by DonaldY** [comment]
貌似支持的，已经用了一年多了。

**Comment by huyixin** [comment]
我这边也有一张word里面的有的图片转pdf丢失了

**Comment by gitchenjh** [comment]
新版本开发中了，默认使用LibreOffice，近期会发布

**Comment by gitchenjh** [comment]
4.0.0版本已替换
