### ISSUE TITLE
最新版本预览需要使用Base64编码的url吗？

### ISSUE THREAD

**Issue by skylinehyc** [kekingcn/kkFileView#197]
最新版本预览需要使用Base64编码的url吗？

**Comment by skylinehyc** [comment]
看了下源码，onlinePreview传入的参数确实是要使用Base64编码的url的，这样升级之后，会导致之前直接使用明文url预览报错啊。。。所以我改了下源码，为了适配之前的项目。

**Comment by zhbdesign** [comment]
> 最新版本预览需要使用Base64编码的url吗？

前端需要怎么修改

**Comment by skylinehyc** [comment]
> > 最新版本预览需要使用Base64编码的url吗？
> 
> 前端需要怎么修改

前端需要对Url进行base64编码，例如：Base64.encode('url'); 即可
