### ISSUE TITLE
openoffice切换libreoffice案例

### ISSUE THREAD

**Issue by WinnerSong** [kekingcn/kkFileView#211]
同事使用过程中发现doc和ppt很简单的图表预览都不能正常显示，下载openoffice和libreoffice桌面客户端打开，测试发现openoffice对图表支持真的不太友好，libreoffice能正常显示。下面分享切换 openoffice到libreoffice流程：
1、基于作者源码中的 Dockerfile 进行构建运行
2、从网站 https://www.libreoffice.org/download/download/?type=deb-x86_64&version=7.1.0&lang=zh-CN 获取 libreoffice 下载链接。我们这里用的 ubuntu，于是要下载 deb 文件。
```
cd /tmp
wget https://www.libreoffice.org/donate/dl/deb-x86_64/7.1.0/zh-CN/LibreOffice_7.1.0_Linux_x86-64_deb.tar.gz
tar -zxvf LibreOffice_7.1.0_Linux_x86-64_deb.tar.gz
dpkg -i /tmp/LibreOffice_7.0.4.2_Linux_x86-64_deb/DEBS/*.deb
```
3、安装后，安装目录在 `/opt/libreoffice7.0`，将该目录配置在配置文件的 office.home。重启服务，查看日志，office 并不能正常启动
4、百度、google 各种资料，就是可以查看 libreoffice 是否可以正常运行 `/opt/libreoffice7.0/program/soffice --help`
![image](https://user-images.githubusercontent.com/15809546/106980704-a291fb80-679b-11eb-8af8-b272a309ef77.png)
发现缺少依赖。
5、安装依赖
执行 `apt-get update`
`apt-get install -y libxinerama1`
再次查看命令是否能够正常运行
![image](https://user-images.githubusercontent.com/15809546/106980943-146a4500-679c-11eb-81ee-fbb2199500d6.png)
继续安装依赖
`apt-get install -y libcairo2`
再次查看命令是否能够正常运行
![image](https://user-images.githubusercontent.com/15809546/106981080-51ced280-679c-11eb-9ab7-c1c7c20e5d22.png)
继续安装依赖
`apt-get install -y libcups2`
再次查看命令是否运行正常
![image](https://user-images.githubusercontent.com/15809546/106981232-9a868b80-679c-11eb-8baf-a46efd59471d.png)
再次安装依赖
`apt-get install -y libx11-xcb1`
查看命令是否运行正常
![image](https://user-images.githubusercontent.com/15809546/106981357-d7eb1900-679c-11eb-8a6c-7ea71f716aa2.png)
5、重启服务，查看日志，无异常，预览文件测试，图表文件正常 -_-
6、配置 Dockerfile
为防止下载比较慢，提前下载好 LibreOffice_7.0.4_Linux_x86-64_deb.tar.gz，跟 Dockerfile 同级目录；
复制并解压文件到镜像 `ADD LibreOffice_7.0.4_Linux_x86-64_deb.tar.gz /tmp/
` ；
添加安装安装依赖命令 `apt-get install -y libxinerama1 libcairo2 libcups2 libx11-xcb1`；
安装 libreoffice `dpkg -i /tmp/LibreOffice_7.0.4.2_Linux_x86-64_deb/DEBS/*.deb`；
把 Dockerfile 相关 openoffice 相关命令操作干掉，重新构建镜像即可，记得使用的时候修改配置中的 office.home 路径

**Comment by gitchenjh** [comment]
官方4.0.0版本后，已切换

**Comment by leolird** [comment]
@gitchenjh @opkcloud  我切到最新的4.0.0版本之后，问题依然存在，首先我确定我本地的libreoffice是好用的，因为我使用命令是可以正常将word/excel 转换成pdf的，最后我把抛异常的代码注释掉了，kkFileView server启动成功，预览测试也都是正常的

**Comment by ygxxii** [comment]
在 CentOS 7 上测试了一下，LibreOffice 的依赖只需要安装 `cairo` 和 `libSM` 就行了，不需要 `yum groupinstall -y  "X Window System"`

```bash
yum -y install cairo libSM
```


P.S. 而且 `X Window System` 这个 yum group 已经不存在了。
