### ISSUE TITLE
想请问下有关 OFD 预览的进展？

### ISSUE THREAD

**Issue by biuaxia** [kekingcn/kkFileView#258]
请问下开发团队有计划支持OFD文档吗？

我在文档找了一遍没有看到ofd已经支持的相关资料。

请问下是有有计划支持此类型的文档呢？

**Comment by gitchenjh** [comment]
3.6 版本后已经支持OFD

**Comment by DLTech21** [comment]
OFD乱码解决了吗

**Comment by biuaxia** [comment]
> OFD乱码解决了吗

使用3.6及之后的版本就行了

**Comment by DLTech21** [comment]
确定能处理内置字体？

**Comment by DLTech21** [comment]
[abc99.zip](https://github.com/kekingcn/kkFileView/files/7472885/abc99.zip)

**Comment by DLTech21** [comment]
> > OFD乱码解决了吗
> 
> 使用3.6及之后的版本就行了

线上demo是3.6版本后的？
