### ISSUE TITLE
压缩文件等预览返回的树形结构问题

### ISSUE THREAD

**Issue by PHINEXLISY** [kekingcn/kkFileView#318]
比如读取zip中的ZipEntry如果不包含**目录文件（isDirectory=true）**，只包含**带有相对路径的文件（isDirectory=false）**的话，输出取根目录** ("") **下的树形数据会有问题。
只会显示一层文件且文件名是**层级_目录名**，而且程序中处理的其他最底层目录的数据会与根目录层级平行

**Comment by PHINEXLISY** [comment]
已自己手动调整，确实是4.0的一个bug问题

**Comment by elarbor** [comment]
![Image](https://github.com/user-attachments/assets/a189e06d-e264-4468-8a78-dcb1a1b1bd75)

https://ask.csdn.net/questions/8226957
