### ISSUE TITLE
部署报错，帮忙看下这个错是什么原因吧 谢谢

### ISSUE THREAD

**Issue by wincentytg** [kekingcn/kkFileView#327]
![44a25eb797b7c9871ffa49604c791a4](https://user-images.githubusercontent.com/4344069/146704465-c7dc8608-fcb1-4622-a510-8d0ade0adb83.png)

**Comment by PHINEXLISY** [comment]
```
ps -ef|grep 2001
ps -ef|grep 2002
./shutdown.sh

```
首先找到2001和2002端口的office组件并且kill（**前提是2001和2002没有被其他应用占用**）
然后杀掉kkfile进程并且重启。

**Comment by zhangyao-zy** [comment]
office组件没装把

**Comment by Ting-xin** [comment]
楼主最后解决了吗

**Comment by Ting-xin** [comment]
> ```
> ps -ef|grep 2001
> ps -ef|grep 2002
> ./shutdown.sh
> ```
> 
> 首先找到2001和2002端口的office组件并且kill（**前提是2001和2002没有被其他应用占用**） 然后杀掉kkfile进程并且重启。

大佬好，我也这个错误，但是我的 2001 2002 端口并没有被占用
