### ISSUE TITLE
关于文档安全问题

### ISSUE THREAD

**Issue by icnz** [kekingcn/kkFileView#355]
问一个文档安全问题，如果只想让预览不想让下载，程序是否可以实现？
目前通过在线demo来看，文档的路径只是经过了base64Encode和encodeURIComponent转换
var url = 'http://127.0.0.1:8080/file/test.txt'; //要预览文件的访问地址
window.open('http://127.0.0.1:8012/onlinePreview?url='+encodeURIComponent(base64Encode(url)));
但是通过decodeURIComponent和base64Decode就可以看到文档的源路径，就可以直接下载了

**Comment by liyanggyang** [comment]
个人感觉其实你这个需求都是伪需求，说的不好听点，现在业内的只能查看不能下载，通过浏览器“打印”或者控制台的full截屏等等方式，一样的下载，。

**Comment by icnz** [comment]
错，这不是伪命题，这是真实的需求。源文档和打印、截图区别还是很大的，源文档不支持下载，打印和截图都会很明白，尤其是涉及通知、公告等内容，那是尤其重要的。不会有拿着鸡毛当令箭或虚假宣传等现象出现，官方可以及时佐证或辟谣。

**Comment by klboke** [comment]
这么定制化的需求自己实现就好

**Comment by icnz** [comment]
然
