### ISSUE TITLE
linux 如何打包了

### ISSUE THREAD

**Issue by lvqibin123** [kekingcn/kkFileView#378]
默认maven打包打的是windows包，请问如何打linux的包了？需要这么修改了？

**Comment by klboke** [comment]
默认两个系统的包都会打吧

**Comment by lvqibin123** [comment]
> 默认两个系统的包都会打吧
应该不是的，打包之后bin目录下只有startup.bat没有.sh的了，估计要进行配置了，再研究一下了。

**Comment by lvqibin123** [comment]
我知道怎么打linux包了，需要注释掉pom.xml第330行的  <descriptor>src/main/assembly/dist-win32.xml</descriptor>，然后打包就是linux的包了。

**Comment by lvqibin123** [comment]
done

**Comment by sofafan** [comment]
请问下，修复后的版本包怎么获取呢。
