### ISSUE TITLE
线上版本无法预览pdf等格式，只能预览图片

### ISSUE THREAD

**Issue by nimcoms** [kekingcn/kkFileView#398]
本地源码运行（内网），用nginx转发到外网，手机访问能在线预览；
丢到远端，就无法预览除图片以外的任何格式；
url是minio的，而且minio也代理了，也能访问；
求大佬帮帮
![image](https://user-images.githubusercontent.com/95084066/198248570-848cbab0-f3be-434a-8f1f-b65799ff64f7.png)

**Comment by 872798774** [comment]
不好意思，打扰各位了，排查了好久，因为我们公司的内网访问不了我们公司的外网，没法把url资源下载到文件里导致的

**Comment by Mallk33** [comment]
> 不好意思，打扰各位了，排查了好久，因为我们公司的内网访问不了我们公司的外网，没法把url资源下载到文件里导致的

我也遇到这个问题了，请问有什么解决方案吗
