### ISSUE TITLE
docker下载了，启动正常。但是curl http://127.0.0.1:8012没有数据

### ISSUE THREAD

**Issue by lizi007** [kekingcn/kkFileView#399]
拉取镜像
docker pull keking/kkfileview
运行
docker run -it -p 8012:8012 keking/kkfileview
然后执行curl http://127.0.0.1:8012/ 并没有首页的数据，返回数据为空，请教一下为什么会这样

**Comment by lizi007** [comment]
- 拉取镜像
docker pull keking/kkfileview
- 运行
docker run -it -p 8012:8012 keking/kkfileview
- 然后执行curl http://127.0.0.1:8012 并没有首页的数据，返回数据为空，请教一下为什么会这样

**Comment by lizi007** [comment]
我使用http://127.0.0.1/office/onlinePreview?url=aHR0cDovLzEwLjEwLjM4LjIyNTo4MDgwL2NvdmVyL3NpeC5qcGVn成功了，但是只能解析图片不能解析其他的报错
该(docx)文件，系统暂不支持在线预览，具体原因如下：
java.security.cert.CertificateException: No subject alternative DNS name matching task.beaconice.com.cn found.

**Comment by iwangbowen** [comment]
因为`127.0.0.1:8012`会重定向到`127.0.0.1:8012/index`，要看到首页结果可以直接`curl 127.0.0.1:8012/index`或`curl -L 127.0.0.1:8012`
