### ISSUE TITLE
[Bug][功能请求]无法浏览自签证书的文件url

### ISSUE THREAD

**Issue by nAnderYang** [kekingcn/kkFileView#409]
测试发现 文件存储在一个 https自签证书的的服务器中，使用kkfileview容器做预览时报错

请求添加强制信任 https 的配置参数

![image](https://user-images.githubusercontent.com/28423384/205600874-d233c645-9aa3-4ceb-82e4-a9bbe502adbd.png)

**Comment by gaoxingzaq** [comment]
4.2版本支持

**Comment by nAnderYang** [comment]
3Q 那就期待下一个版本的发布了
