### ISSUE TITLE
url参数值必须为包含文件后缀的文件名时，才能正常预览，否则会报错。

### ISSUE THREAD

**Issue by yuanzicheng** [kekingcn/kkFileView#429]
是否考虑移除这个检查？因为项目中有时候并不会以文件名去获取文件内容，而是以文件id或文件对应的key去下载文件，不会在url中直接暴露文件名。

**Comment by gaoxingzaq** [comment]
先下载后判断  和先判断类型是否支持在下载的区别 资源浪费

**Comment by alvonwong** [comment]
部署方式里好像有调用方推流这个说明，还没尝试过。

**Comment by yuanzicheng** [comment]
先close吧，个人认为如果只是为了在下载前判断文件类型，完全可以用一个专门的query参数来传递，比如?type=application/pdf，强制使用文件后缀名形式的url，会对业务系统URL的格式产生约束。
