### ISSUE TITLE
官网预览效果与本地跑不一致的问题

### ISSUE THREAD

**Issue by YYYet** [kekingcn/kkFileView#454]
官网的在线体验excel效果如图
![image](https://github.com/kekingcn/kkFileView/assets/44288158/87e6cf3e-b118-4d69-8e0f-3e850d2a0add)
但是我本地编译4.2.1  excel则是直接以html展示，如下
![image](https://github.com/kekingcn/kkFileView/assets/44288158/71ac104b-bdbd-4331-afd7-45643e8740a6)
在源码中未追溯到该控制，请问此次更新未包含该内容还是我遗漏了什么配置

**Comment by skye2j** [comment]
同问

**Comment by gitchenjh** [comment]
官网是master分支最新代码打包的，会比已经发布的版本新
目前官网是4.3.0-SNAPSHOT版本，已发布的稳定版本是4.2.1
