### ISSUE TITLE
未上传的文件不能够直接预览吗

### ISSUE THREAD

**Issue by HanbgCN** [kekingcn/kkFileView#503]
![image](https://github.com/kekingcn/kkFileView/assets/31720493/a8e46e5c-8b50-413f-9417-3bdd79ad2db3)
直接填入的是nginx中的文件， 在浏览器直接输入这个地址，浏览器是可以进行下载的
![image](https://github.com/kekingcn/kkFileView/assets/31720493/66b6efd4-f0cc-4c4d-a46d-54ce95d0233d)
但是，点击预览会报错 
拒绝连接 (Connection refused)
我要是手动上传之后  在输入地址 点击预览就可以了

官网中的文档里没有强调要必须先上传文件再预览的啊  说的都是直接带入encodeURIComponent之后的链接地址就可以 

在预览这一块还是很不明白流程
希望大佬们帮忙解答一下 
感谢！

**Comment by HanbgCN** [comment]
未上传的文件也是可以直接预览的  文件地址是可以被kkFileView服务能够访问到    如果访问不了  大概率提供文件的服务有问题     昨天我就是因为nginx的问题 导致访问失败

**Comment by yumu7777777** [comment]
您好，我的文件能正常访问，但是预览不了，能看下你nginx的配置吗
![image](https://github.com/kekingcn/kkFileView/assets/104643678/1fd145e5-c9a3-412c-99a3-4e91f55f4673)

**Comment by HanbgCN** [comment]
就是把文件放在的nginx的html文件夹下面  nginx承担文件服务器角色  没有其他的配置   之前部署的nginx云主机过期了  找不到了 不好意思哈
