### ISSUE TITLE
打开的文件如果是excel，应该如何设置配置让其仅预览，而不可编辑

### ISSUE THREAD

**Issue by wangenze267** [kekingcn/kkFileView#544]
打开的文件如果是excel，应该如何设置配置让其仅预览，而不可编辑

**Comment by 404-pp** [comment]
请问是如何解决的

**Comment by wangenze267** [comment]
我后来在代码中发现了配置项，文件名字叫做：`officeweb.ftl`，你可以找找看
```
allowEdit: false, // 是否允许前台编辑
```

**Comment by 404-pp** [comment]
![image](https://github.com/user-attachments/assets/4ccbe5ae-1393-45f8-9a25-344f240827c9)
确实不可编辑了，但其实我是想让这些工具栏隐藏，这样也是不让他编辑的方式....

**Comment by wangenze267** [comment]
`showtoolbar` 试试这个属性，另外，双击表格也是修改的一种方式
