### ISSUE TITLE
预览视频能自动播放吗?

### ISSUE THREAD

**Issue by hanqicheng** [kekingcn/kkFileView#545]
如题,我想预览视频后自动播放

**Comment by gaoxingzaq** [comment]
最新源码的播放器是支持的 需要自行修改下模板文件 在重新打包就可以了  官方目前没有把这个功能写到配置文件

**Comment by hanqicheng** [comment]
> 最新的播放器是支持的源码需要自行修改下模板文件在重新资源就可以了官方目前没有把这个功能写到配置文件

请问具体改哪部分内容
