### ISSUE TITLE
预览mp4格式视频黑屏

### ISSUE THREAD

**Issue by hanqicheng** [kekingcn/kkFileView#550]
![image](https://github.com/kekingcn/kkFileView/assets/64473636/d44f30fd-4678-4927-97e1-f463d3d36f0f)
如图,在预览播放mp4格式视频显示黑屏

**Comment by gaoxingzaq** [comment]
编码问题

**Comment by hanqicheng** [comment]
> 编码问题

请问该怎么解决或者避免

**Comment by J-Orange** [comment]
请问怎么解决的
