### ISSUE TITLE
域名预览问题

### ISSUE THREAD

**Issue by dahaiChang** [kekingcn/kkFileView#560]
预览问题

**Comment by gaoxingzaq** [comment]
首先这是源码公开，如果不懂就不要乱说鸟语。

**Comment by dahaiChang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dahaiChang** [comment]
> 首先这是源码提供，如果看不懂JAVA代码，你就是胡说鸟语我们鄙视你。 你贴出哪里有上传到我们服务器的代码。 已经是免费开源的项目了，且行且珍惜吧。 怎么多程序员在使用，你当大家都是傻子不懂看代码吗？

打扰了
