### ISSUE TITLE
[力推求更新] LibreOffice ubuntu 平台已经有no-gui版本packages, 建议更换，大大降低docker镜像体积!

### ISSUE THREAD

**Issue by gowy222** [kekingcn/kkFileView#574]
对应文件:
https://github.com/kekingcn/kkFileView/blob/master/docker/kkfileview-jdk/Dockerfile

no-gui 版本参考: (需要FROM ubuntu:24.04 as base)
https://packages.debian.org/sid/libreoffice-nogui
https://www.ubuntuupdates.org/package/core/mantic/universe/updates/libreoffice-nogui

还能省去很多依赖得安装
apt-get install -y libxrender1 libxinerama1 libxt6 libxext-dev libfreetype6-dev libcairo2 libcups2 libx11-xcb1 libnss3 &&\

**Comment by MangoKernel** [comment]
使用nogui的Libreoffice后，office文档转pdf会丢字体。
使用镜像是基于master代码打包的 keking/kkfileview-base:4.4.0；fonts文件夹通用字体也放了，尝试安装了其他字体文件也不行。测试文档字体使用的MiSans。使用老版本Libreoffice正常，不会丢失字体。
![image](https://github.com/user-attachments/assets/00953e9a-5399-4265-a703-bee210d9c1e7)
