### ISSUE TITLE
关闭缓存 cache.enabled = ${KK_CACHE_ENABLED:false}不生效

### ISSUE THREAD

**Issue by dahaiChang** [kekingcn/kkFileView#583]
关闭缓存 cache.enabled = ${KK_CACHE_ENABLED:false}不生效，发现还是有缓存。
因为我们文件预览加的有访问权限控制，有缓存的话，只要有人有权限预览成功一次，缓存还在的话，没有权限的也可以访问。

**Comment by Mzaxd** [comment]
同样的问题 请问您有解决办法了吗？

**Comment by dahaiChang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Mzaxd** [comment]
> 实在不行改源码，每次重新下载，结合缓存定时清理！

我找到解决办法了 也是看源码发现的 只要前端拼接一个参数就可以了 
![image](https://github.com/user-attachments/assets/f4bf6e30-be84-49de-8209-ee0bf4b6f983)
这样每次访问都不走缓存

**Comment by dahaiChang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dahaiChang** [comment]
好的，回头试试，谢谢
