### ISSUE TITLE
找不到jar

### ISSUE THREAD

**Issue by tao2mi** [kekingcn/kkFileView#8]
你好，发现一个依赖无法下载到
 <groupId>com.yudianbank</groupId>
 <artifactId>jodconverter</artifactId>
 <version>1.0-SNAPSHOT</version>

不好意思，发现这个包来自项目 jodconverter-cor

**Comment by klboke** [comment]
项目pull下来后，mvn install下就好

**Comment by LiZhenNet** [comment]
中央仓库 没这个包，再 install 也没用。
